channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.0.0
  - lightgbm==4.2.0
  - matplotlib==3.8.2
  - numpy==1.26.2
  - packaging==23.2
  - pandas==2.1.4
  - psutil==5.9.0
  - pyarrow==14.0.2
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
