artifact_uri: file:///c:/Users/fathi/OneDrive/OpenClassrooms/P_7_Impl%C3%A9mentez_un_mod%C3%A8le_de_scoring_Metalsi_Fathi/mlruns/730560745696649395/6dcae1def9fc4634b000c7fa947a0b16/artifacts
end_time: 1703925488822
entry_point_name: ''
experiment_id: '730560745696649395'
lifecycle_stage: active
run_id: 6dcae1def9fc4634b000c7fa947a0b16
run_name: welcoming-loon-326
run_uuid: 6dcae1def9fc4634b000c7fa947a0b16
source_name: ''
source_type: 4
source_version: ''
start_time: 1703925196888
status: 3
tags: []
user_id: fathi
