# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to AWS ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: shaaakir281/prediction_projet7:latest

  deploy-to-aws:
    runs-on: ubuntu-latest
    needs: build-and-push  # This ensures that the deploy job starts after the build-and-push job completes
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <your-aws-region>

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t prediction_projet7 -f Dockerfile .
          docker tag prediction_projet7:latest 656647707554.dkr.ecr.us-east-1.amazonaws.com/prediction_projet7:latest
          docker push 656647707554.dkr.ecr.us-east-1.amazonaws.com/prediction_projet7:latest

      - name: Deploy Docker image to AWS ECS
        run: |
           aws ecs update-service --cluster Prediction-Projet-7 --service Prediction-projet-7-service --force-new-deployment
